services:
  mysql:
    image: mysql:9.1
    container_name: prescriptionly-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prescriptionly
    ports:
      - "3306:3306"
    volumes:
      - prescriptionly_mysql_data:/var/lib/mysql

volumes:
  prescriptionly_mysql_data:
